### ISSUE TITLE
adding projects

### ISSUE THREAD

**Issue by Maslor** [ISTecnico/istecni.co#2]
I was just wondering, what kind of projects are accepted in this repo? I might have one or two BSc project implementations, although they're not A++ status. I'm not sure if it's what you're looking for :question:

**Comment by diasdavid** [comment]
I started istecni.co with the goal of incentivising folks to share their hacks and apps and invite others to contribute. It is a old endeavour and not active anymore.

For course project sharing, take a peek at SHELF, there is one for LETI and LEIC and it is the one stop shop for any kind of course projects:
- http://neerci.tecnico.ulisboa.pt/shelf/
- http://neerci.tecnico.ulisboa.pt/shelf-leic/

**Comment by Maslor** [comment]
Alright, thanks!
